CREATE SEQUENCE adoption.adoption_request_forms_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE adoption.adoption_request_forms (
    id                               BIGINT   PRIMARY KEY DEFAULT nextval('adoption.adoption_request_forms_seq'),
    adoption_request_id              BIGINT   NOT NULL,
    has_previous_cat_experience      BOOLEAN  NOT NULL,
    previous_pets_history            TEXT,
    adults_in_household              INTEGER  NOT NULL,
    has_children                     BOOLEAN  NOT NULL,
    children_ages                    VARCHAR(255),
    has_other_pets                   BOOLEAN  NOT NULL,
    other_pets_description           TEXT,
    hours_alone_per_day              INTEGER  NOT NULL,
    stable_housing                   BOOLEAN  NOT NULL,
    housing_instability_reason       TEXT,
    housing_type                     VARCHAR(50)  NOT NULL,
    housing_size                     INTEGER  NOT NULL,
    has_outdoor_access               BOOLEAN  NOT NULL,
    is_rental                        BOOLEAN  NOT NULL,
    rental_pets_allowed              BOOLEAN,
    has_windows_with_view            BOOLEAN  NOT NULL,
    has_vertical_space               BOOLEAN  NOT NULL,
    has_hiding_spots                 BOOLEAN  NOT NULL,
    household_activity_level         VARCHAR(50)  NOT NULL,
    why_cats_need_to_play            TEXT     NOT NULL,
    daily_play_minutes               INTEGER  NOT NULL,
    planned_enrichment               TEXT     NOT NULL,
    reaction_to_unwanted_behavior    TEXT     NOT NULL,
    has_scratching_post              BOOLEAN  NOT NULL,
    willing_to_enrich_environment    BOOLEAN  NOT NULL,
    motivation_to_adopt              TEXT     NOT NULL,
    understands_long_term_commitment BOOLEAN  NOT NULL,
    has_vet_budget                   BOOLEAN  NOT NULL,
    all_household_members_agree      BOOLEAN  NOT NULL,
    anyone_has_allergies             BOOLEAN  NOT NULL,
    allergies_detail                 TEXT,
    created_at                       TIMESTAMP NOT NULL
);