package es.kitti.adoption.event;

import com.fasterxml.jackson.annotation.JsonProperty;

public record AdoptionFormSubmittedEvent(
        @JsonProperty("adoptionRequestId") Long adoptionRequestId,
        @JsonProperty("catId") Long catId,
        @JsonProperty("adopterId") Long adopterId,
        @JsonProperty("organizationId") Long organizationId,
        @JsonProperty("hasPreviousCatExperience") Boolean hasPreviousCatExperience,
        @JsonProperty("previousPetsHistory") String previousPetsHistory,
        @JsonProperty("adultsInHousehold") Integer adultsInHousehold,
        @JsonProperty("hasChildren") Boolean hasChildren,
        @JsonProperty("childrenAges") String childrenAges,
        @JsonProperty("hasOtherPets") Boolean hasOtherPets,
        @JsonProperty("otherPetsDescription") String otherPetsDescription,
        @JsonProperty("hoursAlonePerDay") Integer hoursAlonePerDay,
        @JsonProperty("stableHousing") Boolean stableHousing,
        @JsonProperty("housingInstabilityReason") String housingInstabilityReason,
        @JsonProperty("housingType") String housingType,
        @JsonProperty("housingSize") Integer housingSize,
        @JsonProperty("hasOutdoorAccess") Boolean hasOutdoorAccess,
        @JsonProperty("isRental") Boolean isRental,
        @JsonProperty("rentalPetsAllowed") Boolean rentalPetsAllowed,
        @JsonProperty("hasWindowsWithView") Boolean hasWindowsWithView,
        @JsonProperty("hasVerticalSpace") Boolean hasVerticalSpace,
        @JsonProperty("hasHidingSpots") Boolean hasHidingSpots,
        @JsonProperty("householdActivityLevel") String householdActivityLevel,
        @JsonProperty("whyCatsNeedToPlay") String whyCatsNeedToPlay,
        @JsonProperty("dailyPlayMinutes") Integer dailyPlayMinutes,
        @JsonProperty("plannedEnrichment") String plannedEnrichment,
        @JsonProperty("reactionToUnwantedBehavior") String reactionToUnwantedBehavior,
        @JsonProperty("hasScratchingPost") Boolean hasScratchingPost,
        @JsonProperty("willingToEnrichEnvironment") Boolean willingToEnrichEnvironment,
        @JsonProperty("motivationToAdopt") String motivationToAdopt,
        @JsonProperty("understandsLongTermCommitment") Boolean understandsLongTermCommitment,
        @JsonProperty("hasVetBudget") Boolean hasVetBudget,
        @JsonProperty("allHouseholdMembersAgree") Boolean allHouseholdMembersAgree,
        @JsonProperty("anyoneHasAllergies") Boolean anyoneHasAllergies,
        @JsonProperty("allergiesDetail") String allergiesDetail
) {}
